name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  pull_request:
    branches: 
      - 'main'

jobs:
  build:
    runs-on: [ ubuntu-latest ]

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: npm install
        run: npm install

      - name: npm build
        run: npm run build

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
        
      - name: docker build
        run: docker build -t ghcr.io/${{ github.repository }}/my-image:latest .

      - name: docker push
        run: docker push ghcr.io/${{ github.repository }}/my-image:latest
